version: "3"
services:
  mymongodb:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mymongodb
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - sangam
  frontend:
    build:
      dockerfile: dockerfile
      context: ./frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - sangam
    depends_on:
      - backend
networks:
  sangam:
    driver: bridge