---
- name: Deploying Project.
  hosts: localhost
  tasks:
    # - name: Start docker service
    #   service:
    #     name: docker
    #     state: started

    # - name: pull frontend docker image
    #   shell: /usr/local/bin/docker pull docker.io/gaparul/sangam-alumniportal-frontend:latest

    # - name: pull backend docker image
    #   shell: /usr/local/bin/docker pull docker.io/gaparul/sangam-alumniportal-backend:latest

    # - name: Copy Docker Compose file from host machine
    #   copy:
    #     src: ./docker-compose.yml
    #     dest: /Users/harsh/Desktop/Sangam-AlumniPortal/docker-compose.yml
    - name:
      shell: /usr/local/bin/docker-compose -f docker-compose.yml up

    # - name: Pull Frontend image
    #   docker_image:
    #     name: gaparul/sangam-alumniportal-frontend
    #     source: pull
    # - name: Pull Backend image
    #   docker_image:
    #     name: gaparul/sangam-alumniportal-backend
    #     source: pull