---
- name: Deploying Project.
  hosts: localhost
  tasks:
    # - name: Start docker service
    #   service:
    #     name: docker
    #     state: started

    - name: pull frontend docker image
      shell: /usr/local/bin/docker pull docker.io/gaparul/sangam-alumniportal-frontend:latest

    - name: pull backend docker image
      shell: /usr/local/bin/docker pull docker.io/gaparul/sangam-alumniportal-backend:latest

    # - name: Pull Frontend image
    #   docker_image:
    #     name: gaparul/sangam-alumniportal-frontend
    #     source: pull
    # - name: Pull Backend image
    #   docker_image:
    #     name: gaparul/sangam-alumniportal-backend
    #     source: pull