---
- name: Deploying Project.
  hosts: localhost
  tasks:
    - name: Copy Docker Compose file from host machine
      copy:
        src: ./docker-compose.yml
        dest: /Users/harsh/Desktop/Sangam-AlumniPortal/docker-compose.yml

    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /Users/harsh/Desktop/Sangam-AlumniPortal
        files:
        - docker-compose.yml